#!/usr/bin/env bash

if uname -a | grep -iq ubuntu; then
  sudo apt-get install -y build-essential libosmesa6-dev

  curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  sudo apt-get install -y nodejs

  sudo npm install -g webpack babel-cli

  npm install

  git submodule foreach --recursive git checkout master

  cd scripts/LAStools/LASzip
  mkdir build && cd build
  cmake -DCMAKE_BUILD_TYPE=Release ..
  make -j

  cd ../../../..

  cd scripts/PotreeConverter
  mkdir build && cd build
  cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=../../LAStools/LASzip/dll -DLASZIP_LIBRARY=$(pwd)/../../LAStools/LASzip/build/src/liblaszip.so ..
  make -j

  cd ../../..

  cp -R scripts/PotreeConverter/PotreeConverter/resources scripts/PotreeConverter/build/PotreeConverter

  cd scripts/im2ply
  mkdir build && cd build
  cmake ..
  make -j

  cd ../../..
else
  echo 'Please use Ubuntu for now!'
fi